"""Render the human-readable brief from the same profile the plan is built from.

The brief and the plan cannot disagree: both are rendered from one ``Profile``, and the
"what changes if you state it" section is computed by diffing profiles rather than written by
hand. Nothing here invents an answer: an input that was not supplied is printed as unstated, and
the brief says what stating it would change.
"""

from __future__ import annotations

from . import __version__
from .format import PLAN_VERSION
from .intent import FLAGS, QUESTIONS, SiteIntent
from .kinds import (
    SOURCES,
    SURFACE_BASIS,
    Profile,
    advice_for,
    changes,
    tensions,
    with_flag,
)

WHAT_THIS_IS = """## What this brief is

This is a statement of intent to build against. It records the decisions that are cheap once and
expensive later: which Schema.org entities describe this site, which machine-readable surfaces it
publishes, what shape its URLs take, how it treats crawlers, and what each page is for.

**A plan is a statement of intent. It does not predict whether an agent will find, understand or
recommend the site.** `siteplan check` passing means the file follows the plan format; a
`sitewalk --plan` run passing means a built site matches the plan. Neither is evidence of success,
traffic, ranking or citation. This tool measured nothing about any live site: it asked questions
and wrote files.

Every recommendation below carries one of two labels:

- **published practice** - it rests on a citable standard, specification or vendor documentation,
  named in the reason. You can check it.
- **our judgement** - no published source settles it. It is our reading of what this kind of site
  needs, and you are entitled to discount it.

Where a recommendation has both a published and a judged component, the label names the component
that decides it, and the reason names the other.
"""

FLAG_LABELS: dict[str, str] = {
    "sells": "Sells something directly (`--sells` / `--no-sells`)",
    "local": "Serves a local area (`--local` / `--not-local`)",
    "publishes": "Publishes content for readers (`--publishes` / `--no-publishes`)",
    "bookings": "Can take a booking (`--takes-bookings` / `--no-takes-bookings`)",
}


def _code(names: tuple[str, ...]) -> str:
    return ", ".join(f"`{name}`" for name in names)


def _maybe_code(value: str | None) -> str:
    return f"`{value}`" if value else "**unstated**"


def _answer(value: bool | None) -> str:
    if value is None:
        return "**unstated**"
    return "yes" if value else "no"


def _inputs_table(intent: SiteIntent) -> list[str]:
    """The input rows, header excluded: the call site owns the heading."""
    rows = [
        ("Site", intent.source("site"), _maybe_code(intent.site)),
        ("Name", intent.source("name"), _maybe_code(intent.name)),
        ("Kind", intent.source("kind"), f"`{intent.kind}`"),
    ]
    for flag in FLAGS:
        rows.append((QUESTIONS[flag].rstrip("?"), intent.source(flag), _answer(intent.answer(flag))))
    return [f"| {label} | {source} | {value} |" for label, source, value in rows]


def _unstated_lines(intent: SiteIntent, base: Profile) -> list[str]:
    """One row per unstated input, generated by diffing the profiles it would produce."""
    lines = ["| Not stated | If you answer yes | If you answer no |", "| --- | --- | --- |"]
    any_unstated = False
    for flag in FLAGS:
        if intent.answer(flag) is not None:
            continue
        any_unstated = True
        yes = changes(base, with_flag(base, flag, True))
        no = changes(base, with_flag(base, flag, False))
        yes_text = "; ".join(yes) if yes else "nothing changes in this plan"
        no_text = "; ".join(no) if no else "nothing changes in this plan"
        lines.append(f"| {FLAG_LABELS[flag]} | {yes_text} | {no_text} |")
    if not any_unstated:
        return ["Every input was stated on the command line or at the prompt."]
    return lines


def _advice_lines(profile: Profile, group: str) -> list[str]:
    return [
        f"  Basis: {item.basis}. {item.why}"
        for item in advice_for(profile)
        if item.group == group
    ]


def _url_shape(profile: Profile) -> str:
    parts = [
        "lowercase paths" if profile.urls.lowercase else "paths as written",
        "no trailing slash" if profile.urls.trailing_slash == "never" else "always a trailing slash",
        f"no page deeper than {profile.urls.max_depth} path segments",
    ]
    return "; ".join(parts)


def render(intent: SiteIntent, base: Profile, profile: Profile, notes: tuple[str, ...] = ()) -> str:
    """Render the brief for one run. ``base`` is the kind's profile before any flag was applied."""
    title = intent.name or intent.site or "Untitled site"
    lines: list[str] = [f"# {title} - agent-first design brief", ""]
    lines.append(f"- **Site**: {_maybe_code(intent.site)}")
    lines.append(f"- **Kind**: `{profile.kind}` - {profile.headline}")
    if intent.name:
        lines.append(f"- **Name**: {intent.name}")
    lines.append(f"- **Plan file**: `site.json` (`plan_version` {PLAN_VERSION})")
    lines.append(
        f"- **Generated by**: `siteplan` {__version__} - standard library only, no network, "
        "nothing fetched. Every input it had is listed below."
    )
    lines += ["", WHAT_THIS_IS.rstrip()]

    lines += ["", "## Inputs", "", "| Input | Where it came from | Answer |", "| --- | --- | --- |"]
    lines += _inputs_table(intent)

    findings = list(notes) + [f"**The kind and an answer do not fit.** {item}" for item in tensions(profile, intent)]
    if findings:
        lines += ["", "## Notes on the inputs", ""]
        lines += [f"- {item}" for item in findings]

    lines += [
        "",
        "## What was not stated, and what changes if you state it",
        "",
        "Nothing here is filled in for you. Each row says what the plan would do if you answered.",
        "",
    ]
    lines += _unstated_lines(intent, base)

    lines += ["", "## The decisions", "", profile.rationale, ""]
    lines += ["### 1. Identity - what this site is", ""]
    lines.append(f"- **Schema.org @type**: {_code(profile.identity_types)}")
    lines += _advice_lines(profile, "identity_types")
    lines.append(f"- **Fields to expose**: {_code(profile.identity_fields)}")
    lines += _advice_lines(profile, "identity_fields")

    lines += ["", "### 2. Offering - what it provides", ""]
    lines.append(f"- **Schema.org @type**: {_code(profile.offering_types)}")
    lines += _advice_lines(profile, "offering_types")
    lines.append(f"- **Fields to expose**: {_code(profile.offering_fields)}")
    lines += _advice_lines(profile, "offering_fields")

    lines += [
        "",
        "### 3. Machine-readable surfaces",
        "",
        "The plan requires these. `required_surfaces` in `site.json` carries exactly these names.",
        "",
        "| Surface | Basis | Why this site needs it |",
        "| --- | --- | --- |",
    ]
    for surface in profile.surfaces:
        basis, published = SURFACE_BASIS[surface.name]
        lines.append(f"| `{surface.name}` | {basis} | {published} {surface.reason} |")

    lines += ["", "### 4. URL rules", ""]
    lines.append(f"- **Shape**: {_url_shape(profile)}")
    lines += _advice_lines(profile, "urls")

    lines += ["", "### 5. Crawler stance", ""]
    lines.append(f"- **Stance**: `{profile.crawler_stance}`")
    lines += _advice_lines(profile, "crawler")

    lines += [
        "",
        "### 6. Pages",
        "",
        "| Path | Purpose |",
        "| --- | --- |",
    ]
    for path, purpose in profile.pages:
        lines.append(f"| `{path}` | {purpose} |")
    lines += _advice_lines(profile, "pages")

    lines += [
        "",
        "## What this brief does not claim",
        "",
        "- It does not predict whether an agent will find, understand or recommend this site.",
        "- It does not measure anything about a live site, and it fetched nothing.",
        "- It does not rank the labels: a `published practice` recommendation can still be wrong "
        "for this site, and an `our judgement` one can still be right.",
        "- It does not fill in what you did not say. An unstated input stays unstated above, and "
        "the plan below is the kind's recommendation, not your answer.",
        "- It does not build, scaffold or generate anything. It writes two files.",
        "",
        "## How to use it",
        "",
        "```sh",
        "python3 -m siteplan check site.json   # this file follows the plan format",
        "sitewalk --plan site.json             # a built site reports against these decisions",
        "```",
        "",
        "Neither check is evidence of success. The plan is a gate for the build, not a claim "
        "about the world.",
    ]

    body = "\n".join(lines)
    used = [
        (name, where)
        for name, where in SOURCES
        if name in body
    ]
    if used:
        body += "\n\n## Sources for the published-practice claims\n\n"
        body += "\n".join(f"- **{name}** - {where}" for name, where in used)
    return body + "\n"
